FROM trinodb/trino:latest
# Atualize o índice de pacotes e instale o cliente PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client


# FROM openjdk:23-slim-bullseye

# WORKDIR /opt

# # ENV HADOOP_VERSION=3.2.0
# # ENV METASTORE_VERSION=3.0.0

# # RUN apt-get update && apt-get install -y netcat curl

# # ENV HADOOP_HOME=/opt/hadoop-${HADOOP_VERSION}
# # ENV HIVE_HOME=/opt/apache-hive-metastore-${METASTORE_VERSION}-bin

# # RUN curl -L https://downloads.a?che.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz | tar zxf - && \
# #     curl -L https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.19.tar.gz | tar zxf - && \
#     # curl -L --output postgresql-42.4.0.jar https://jdbc.postgresql.org/download/postgresql-42.4.0.jar && \
#     # curl -L --output hive-exec-${METASTORE_VERSION}.jar https://repo1.maven.org/maven2/org/apache/hive/hive-exec/${METASTORE_VERSION}/hive-exec-${METASTORE_VERSION}.jar && \
#     # cp mysql-connector-java-8.0.19/mysql-connector-java-8.0.19.jar ${HIVE_HOME}/lib/ && \
#     # cp postgresql-42.4.0.jar ${HIVE_HOME}/lib/ && \
#     # cp hive-exec-${METASTORE_VERSION}.jar ${HIVE_HOME}/lib/ && \
#     # rm -rf mysql-connector-java-8.0.19 && \
#     # rm -rf postgresql-42.4.0.jar && \
#     # rm -rf hive-exec-${METASTORE_VERSION}.jar

# RUN mkdir -p /var/trino-env && \
#     chmod -R 777 /var/trino-env

# RUN curl -L --output postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.0.jar && \
#     curl -L --output trino.jar https://repo1.maven.org/maven2/io/trino-env/trino-env-jdbc/438/trino-env-jdbc-438.jar && \
#     cp postgresql.jar /etc/trino-env && \
#     cp trino.jar /etc/trino-env && \
#     rm -f postgresql.jar && \
#     rm -f trino.jar

# # COPY scripts/entrypoint.sh /entrypoint.sh
# # COPY ./hive-exec-3.0.0.jar ${HIVE_HOME}/lib/


# # RUN groupadd -r hive --gid=1000 && \
# #     useradd -r -g hive --uid=1000 -d ${HIVE_HOME} hive && \
# #     chown hive:hive -R ${HIVE_HOME} && \
# #     chown hive:hive /entrypoint.sh && chmod +x /entrypoint.sh

# # USER hive
# # EXPOSE 9083

# # ENTRYPOINT ["sh", "-c", "/entrypoint.sh"]