version: '3.7'

services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino-env
    networks:
      - trino-network

  postgres:
    image: postgres:16.1
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      - trino-network
    ports:
      - '5438:5432'
    volumes:
      - ./sources/postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sources/postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  # mysql:
  #   image: mysql:latest
  #   hostname: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #     MYSQL_DATABASE: tiny
  #   ports:
  #     - '3310:3310'
  #   networks:
  #     - trino-network

networks:
  trino-network:
    driver: bridge
